services:
    postgres:
        container_name: "spring-boot-template-db"
        image: "postgres:latest"
        env_file:
            - .env
        environment:
            - "POSTGRES_DB=${POSTGRES_DB}"
            - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
            - "POSTGRES_USER=${POSTGRES_USER}"
        ports:
            - "5432:5432"
